export enum KycUploadStatusEnum{
    NONE = 'NONE',
    NIN = 'NIN',
    LICENSE = 'LICENSE',
    COMPLETED = 'COMPLETED',
    VEHICLE_DETAILS = 'VEHICLE_DETAILS',
    VEHICLE_IMAGES = 'VEHICLE_IMAGES',
    DRIVER_ADDRESS = 'DRIVER_ADDRESS',
    NEXT_OF_KIN = 'NEXT_OF_KIN',
}
